yarnPath: ".yarn/releases/yarn-berry.js"
npmRegistries:
  https://registry.yarnpkg.com/:
    npmAlwaysAuth: false
npmScopes:
  richnav:
    npmRegistryServer: https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices/npm/registry/
    npmAlwaysAuth: false
