name: Rich Code Nav Indexer
description: Indexes a repo to the Rich Code Nav cloud service
author: Microsoft
branding:
  icon: git-merge
  color: yellow

inputs:
  service-token:
    description: The token used when submitting the index to the Rich Code Nav service. Only necessary for repositories not already invited.
    required: false
  repo-token:
    description: Your GITHUB_TOKEN. Only necessary for private repositories.
    required: false
  languages:
    description: List of languages to use when discovering repository symbols, separated by ','
    required: false
  nugetFeed:
    description: Feed source to use when installing Rich Code Navigation NuGet packages
    required: false
  environment:
    description: 'The Rich Code Navigation environment to upload the index to. One of: production, staging or development.'
    required: false
  richNavLogOutputDirectory:
    description: A comma-separated list of log files created from the build when RichCodeNav.EnvVarDump is a package reference
    required: false

outputs:
  lspLogsPath:
    description: The path to LSP logs that may be uploaded as an artifact for diagnostics.

runs:
  using: node12
  main: lib/yarn-bootstrap.js
