name: Release new version
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: create PR
      run: gh pr create -H main -B v0.1 --title 'new release' --body 'Auto-created from merge into main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
